[package]
name = "ultrack-td"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[lib]
name = "_rustlib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
numpy = "0.25.0"
petgraph = "0.8"
rand = "0.9.2"